#!/usr/bin/env node
/**
 * Normalizes `@/…` imports in `src/` to relative paths.
 *
 * Runs automatically as the `preformat` step, before Prettier sorts imports.
 *
 * Why this direction: the `@` alias is only configured for the desktop app
 * (`vite.config.ts`, `vitest.config.ts`, `tsconfig.json`). The Android
 * companion in `apps/mobile-android/` imports 36 modules directly out of
 * `src/` through relative paths and has no alias of its own, so any `@/`
 * import inside a module the Android bundle pulls in fails to resolve.
 * Relative paths work for every consumer, which is also what the overwhelming
 * majority of the codebase already uses.
 *
 * `src/components/ui/` is excluded: those files are generated by
 * `pnpm dlx shadcn@latest add`, and `components.json` configures the `@/`
 * aliases they ship with. Rewriting them would be undone by the next
 * regeneration, and the Android bundle does not import them.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = path.join(repoRoot, 'src');
const SKIP_DIRS = new Set(['node_modules', 'dist', 'generated']);
/** Directories owned by a generator; see the note above. */
const SKIP_PATHS = new Set([path.join(srcDir, 'components', 'ui')]);
const FILE_PATTERN = /\.(ts|tsx|js|jsx|mjs|cjs)$/;

/** Import, `export … from`, and dynamic `import()` specifiers starting with `@/`. */
const SPECIFIER_PATTERNS = [
  /(\bimport\s+(?:type\s+)?(?:[\w*\s{},]*\s+from\s+)?['"])(@\/[^'"]+)(['"])/g,
  /(\bexport\s+(?:\*|\{[^}]*\})\s+from\s+['"])(@\/[^'"]+)(['"])/g,
  /(\bimport\s*\(\s*['"])(@\/[^'"]+)(['"])/g,
];

function collectFiles(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      const child = path.join(dir, entry.name);
      if (!SKIP_DIRS.has(entry.name) && !SKIP_PATHS.has(child)) collectFiles(child, out);
    } else if (FILE_PATTERN.test(entry.name)) {
      out.push(path.join(dir, entry.name));
    }
  }
  return out;
}

function toRelative(fromFile, aliasPath) {
  const target = path.join(srcDir, aliasPath.slice('@/'.length));
  let rel = path.relative(path.dirname(fromFile), target).split(path.sep).join('/');
  if (!rel.startsWith('.')) rel = `./${rel}`;
  return rel;
}

let changedFiles = 0;
let changedImports = 0;

for (const file of collectFiles(srcDir)) {
  const original = fs.readFileSync(file, 'utf8');
  let next = original;

  for (const pattern of SPECIFIER_PATTERNS) {
    next = next.replace(pattern, (_match, prefix, aliasPath, suffix) => {
      changedImports += 1;
      return `${prefix}${toRelative(file, aliasPath)}${suffix}`;
    });
  }

  if (next !== original) {
    fs.writeFileSync(file, next);
    changedFiles += 1;
  }
}

console.log(
  changedFiles === 0
    ? 'fix-imports: no @/ imports found in src/'
    : `fix-imports: rewrote ${changedImports} import(s) in ${changedFiles} file(s)`,
);
