/**
 * Curated emoji set for the chat picker. Kept local and small instead of a
 * full Unicode dataset: each entry is `[emoji, search keywords]`.
 */
export type EmojiEntry = readonly [emoji: string, keywords: string];
export interface EmojiCategory {
  id: string;
  label: string;
  emojis: readonly EmojiEntry[];
}

/** Teams-style quick reactions shown on message hover. */
export const QUICK_REACTIONS = ['👍', '❤️', '😂', '😮', '😢', '🙏'] as const;

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys',
    emojis: [
      ['😀', 'grin smile happy'],
      ['😃', 'smile happy joy'],
      ['😄', 'smile laugh happy'],
      ['😁', 'grin beam'],
      ['😆', 'laugh squint'],
      ['😅', 'sweat laugh relief'],
      ['🤣', 'rofl rolling laugh'],
      ['😂', 'joy tears laugh lol'],
      ['🙂', 'slight smile'],
      ['🙃', 'upside down silly'],
      ['😉', 'wink'],
      ['😊', 'blush smile'],
      ['😇', 'angel innocent halo'],
      ['🥰', 'love hearts adore'],
      ['😍', 'heart eyes love'],
      ['🤩', 'star struck wow'],
      ['😘', 'kiss blow'],
      ['😋', 'yum tasty'],
      ['😜', 'wink tongue crazy'],
      ['🤪', 'zany crazy'],
      ['🤓', 'nerd geek glasses'],
      ['😎', 'cool sunglasses'],
      ['🥳', 'party celebrate'],
      ['🤗', 'hug hugging'],
      ['🤔', 'thinking hmm'],
      ['🤨', 'raised eyebrow skeptical'],
      ['😐', 'neutral meh'],
      ['😑', 'expressionless'],
      ['🙄', 'eye roll'],
      ['😏', 'smirk'],
      ['😬', 'grimace awkward'],
      ['😌', 'relieved calm'],
      ['😴', 'sleep tired zzz'],
      ['🤤', 'drool'],
      ['😷', 'mask sick'],
      ['🤒', 'fever ill'],
      ['🤯', 'mind blown exploding'],
      ['🥱', 'yawn bored'],
      ['😕', 'confused'],
      ['😟', 'worried'],
      ['😮', 'surprised wow open mouth'],
      ['😲', 'astonished shocked'],
      ['🥺', 'pleading puppy eyes'],
      ['😢', 'cry sad tear'],
      ['😭', 'sob crying'],
      ['😱', 'scream fear'],
      ['😤', 'triumph huff'],
      ['😡', 'angry mad rage'],
      ['🤬', 'cursing swear'],
      ['😈', 'devil smiling'],
      ['💀', 'skull dead'],
      ['🤡', 'clown'],
      ['👻', 'ghost boo'],
      ['🤖', 'robot bot'],
    ],
  },
  {
    id: 'gestures',
    label: 'People & gestures',
    emojis: [
      ['👍', 'thumbs up yes like approve +1'],
      ['👎', 'thumbs down no dislike -1'],
      ['👌', 'ok perfect'],
      ['✌️', 'victory peace'],
      ['🤞', 'fingers crossed luck'],
      ['🤟', 'love you'],
      ['🤘', 'rock on'],
      ['🤙', 'call me shaka'],
      ['👋', 'wave hello hi bye'],
      ['🖐️', 'hand raised five'],
      ['✋', 'raised hand stop high five'],
      ['👏', 'clap applause'],
      ['🙌', 'raising hands hooray'],
      ['👐', 'open hands'],
      ['🤝', 'handshake deal agree'],
      ['🙏', 'pray please thanks folded hands'],
      ['💪', 'muscle strong flex'],
      ['👈', 'point left'],
      ['👉', 'point right'],
      ['👆', 'point up'],
      ['👇', 'point down'],
      ['☝️', 'index up one'],
      ['✍️', 'writing'],
      ['👀', 'eyes look see'],
      ['🧠', 'brain smart'],
      ['🙋', 'raising hand question'],
      ['🤷', 'shrug dunno'],
      ['🤦', 'facepalm'],
      ['🙇', 'bow sorry'],
      ['💁', 'tipping hand info'],
      ['🧑‍💻', 'technologist developer coder laptop'],
      ['👨‍👩‍👧‍👦', 'family'],
    ],
  },
  {
    id: 'hearts',
    label: 'Hearts & symbols',
    emojis: [
      ['❤️', 'heart love red'],
      ['🧡', 'orange heart'],
      ['💛', 'yellow heart'],
      ['💚', 'green heart'],
      ['💙', 'blue heart'],
      ['💜', 'purple heart'],
      ['🖤', 'black heart'],
      ['🤍', 'white heart'],
      ['💔', 'broken heart'],
      ['💕', 'two hearts'],
      ['💖', 'sparkling heart'],
      ['💯', 'hundred perfect'],
      ['✅', 'check done yes'],
      ['☑️', 'ballot check'],
      ['❌', 'cross no wrong'],
      ['❗', 'exclamation important'],
      ['❓', 'question'],
      ['⚠️', 'warning caution'],
      ['🚫', 'prohibited no'],
      ['🔥', 'fire hot lit'],
      ['✨', 'sparkles shiny new'],
      ['⭐', 'star favorite'],
      ['🌟', 'glowing star'],
      ['⚡', 'zap lightning fast'],
      ['💡', 'idea bulb'],
      ['🎯', 'target bullseye goal'],
      ['📌', 'pin pushpin'],
      ['🔔', 'bell notification'],
      ['💬', 'speech chat comment'],
      ['➕', 'plus add'],
      ['1️⃣', 'one keycap'],
      ['2️⃣', 'two keycap'],
      ['3️⃣', 'three keycap'],
    ],
  },
  {
    id: 'activities',
    label: 'Celebration & activities',
    emojis: [
      ['🎉', 'tada party celebrate congrats'],
      ['🎊', 'confetti'],
      ['🎈', 'balloon'],
      ['🎁', 'gift present'],
      ['🏆', 'trophy win'],
      ['🥇', 'gold medal first'],
      ['🚀', 'rocket launch ship'],
      ['🎂', 'birthday cake'],
      ['☕', 'coffee break'],
      ['🍕', 'pizza'],
      ['🍔', 'burger'],
      ['🍺', 'beer cheers'],
      ['🥂', 'cheers toast'],
      ['🍰', 'cake'],
      ['⚽', 'soccer football'],
      ['🎮', 'game controller'],
      ['🎵', 'music note'],
      ['🎨', 'art palette design'],
      ['📷', 'camera photo'],
      ['🌈', 'rainbow'],
      ['☀️', 'sun sunny'],
      ['🌙', 'moon night'],
      ['❄️', 'snow cold'],
      ['🌧️', 'rain'],
      ['🐶', 'dog puppy'],
      ['🐱', 'cat kitty'],
      ['🦄', 'unicorn'],
      ['🐢', 'turtle slow'],
      ['🌱', 'seedling grow'],
      ['🌸', 'blossom flower'],
    ],
  },
  {
    id: 'objects',
    label: 'Work & objects',
    emojis: [
      ['💻', 'laptop computer'],
      ['🖥️', 'desktop computer'],
      ['📱', 'phone mobile'],
      ['⌨️', 'keyboard'],
      ['📝', 'memo note write'],
      ['📄', 'document page'],
      ['📁', 'folder'],
      ['📊', 'chart bar stats'],
      ['📈', 'chart up growth'],
      ['📉', 'chart down'],
      ['📅', 'calendar date'],
      ['⏰', 'alarm clock time'],
      ['⏳', 'hourglass wait'],
      ['📎', 'paperclip attach'],
      ['🔗', 'link chain'],
      ['🔒', 'lock secure'],
      ['🔑', 'key'],
      ['🛠️', 'tools build fix'],
      ['🐛', 'bug'],
      ['🧪', 'test experiment'],
      ['📦', 'package box ship'],
      ['✉️', 'envelope mail'],
      ['📣', 'megaphone announce'],
      ['🗓️', 'spiral calendar schedule'],
      ['🧾', 'receipt'],
      ['💰', 'money bag'],
      ['🏠', 'home house'],
      ['✈️', 'airplane travel'],
      ['🚗', 'car'],
      ['🌍', 'globe world earth'],
    ],
  },
];
