[package]
name = "collab-live"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
collab-documents = { path = "../collab-documents" }
collab-protocol = { path = "../collab-protocol" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
yrs.workspace = true
